### ISSUE TITLE
Minimum python version not documented

### ISSUE THREAD

**Issue by gdevenyi** [NVIDIA/build-system-archive-import-examples#11]
The copytree call uses `dirs_exist_ok` which was only introduced in 3.8, earlier versions will error:
```
Archives:
:: tar: cuda_cccl-linux-x86_64-11.4.122-archive.tar.xz
  -> Extracted: cuda_cccl-linux-x86_64-11.4.122-archive/
Traceback (most recent call last):
  File "./parse_redist.py", line 292, in <module>
    post_action()
  File "./parse_redist.py", line 173, in post_action
    flatten_tree(topdir, OUTPUT + "/" + platform, binTag)
  File "./parse_redist.py", line 84, in flatten_tree
    shutil.copytree(src, dest, symlinks=1, dirs_exist_ok=1, ignore_dangling_symlinks=1)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'
```

**Comment by kmittman** [comment]
Hi @gdevenyi 
Python 3.7 and earlier are EOL according to https://devguide.python.org/versions/
Which Python version and/or Linux distro is this on?

**Comment by gdevenyi** [comment]
This was on Ubuntu 18.04, but that's not the issue, the issue is the undocumented dependency.

**Comment by kmittman** [comment]
I've added a note to the [README](../blob/main/README.md)
> note: for this reference script, Python 3.8 or later is required

As well as a check in the Python script itself for the minimum version.

**Comment by kmittman** [comment]
Moreover, I have a bash version of the script that I'm preparing to publish soon.
